services:
  - type: web
    name: todo-list-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
